# This is a basic workflow to help you get started with Actions

name: latexmk

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Github Action for LaTeX
        # You may pin to the exact commit or the version.
        # uses: xu-cheng/latex-action@fea2c87db829f594ce87348291f235074ffd8eeb
        uses: xu-cheng/latex-action@v2
        with:
          # The root LaTeX file to be compiled
          root_file: principal.tex
          # Arbitrary bash codes to be executed before compiling LaTeX documents. Optional
          #pre_compile: pdflatex -file-line-error -interaction=nonstopmode "principal.tex"; bibtex "principal.aux"; makeindex "principal" && makeindex "principal.nlo" -s nomencl.ist -o "principal.nls" 
          # Arbitrary bash codes to be executed after compiling LaTeX documents. Optional
          post_compile: ls -lh *.pdf
          # The LaTeX engine to be invoked. Optional, default is latexmk
          #compiler:
          # The working directory for the LaTeX engine. Optional
          #working_directory:
          # Extra arguments to be passed to the LaTeX engine
          #args: # optional, default is -pdf -file-line-error -halt-on-error -interaction=nonstopmode
          # [Deprecated] Optional. Install extra packages by sudo tlmgr install
          #extra_packages:
          # Optional. Install extra packages by apk
          #extra_system_packages:

      # Includes the AsciiDoctor GitHub Pages Action to convert adoc files to html and publish to gh-pages branch
      - name: asciidoctor-ghpages
        uses: manoelcampos/asciidoctor-ghpages-action@v2
        with:
          asciidoctor_params: #--attribute=nofooter
          pdf_build: false          
